export const DOSAGE_FORM_ICON: Record<string, string> = {
  // Tablets
  tablet: "tablet",
  tablets: "tablet",
  "film coated tablet": "tablet",
  "film-coated tablet": "tablet",
  "effervescent tablet": "tablet",
  "chewable tablet": "tablet",
  "dispersible tablet": "tablet",
  "sugar coated tablet": "tablet",
  "sugar-coated tablet": "tablet",
  "sublingual tablet": "tablet",
  "gastro-resistant tablet": "tablet",
  "modified release tablet": "tablet",
  "extended release tablet": "tablet",
  "sustained release tablet": "tablet",
  "delayed release tablet": "tablet",
  "orodispersible tablet": "tablet",
  "buccal tablet": "tablet",
  "vaginal tablet": "tablet",
  lozenge: "tablet",
  "effervescent granules": "tablet",

  // Capsules
  capsule: "capsule",
  capsules: "capsule",
  "soft gelatin capsule": "capsule",
  "soft gel capsule": "capsule",
  "hard capsule": "capsule",
  "hard gelatin capsule": "capsule",
  "modified release capsule": "capsule",
  "extended release capsule": "capsule",
  "sustained release capsule": "capsule",
  "gastro-resistant capsule": "capsule",
  "enteric coated capsule": "capsule",

  // Liquids / Syrups
  syrup: "syrup",
  suspension: "syrup",
  "oral suspension": "syrup",
  "dry suspension": "syrup",
  "oral solution": "syrup",
  solution: "syrup",
  elixir: "syrup",
  mixture: "syrup",
  linctus: "syrup",
  "oral drops": "drop",
  "pediatric drops": "drop",
  "paediatric drops": "drop",
  emulsion: "syrup",
  concentrate: "syrup",
  "oral liquid": "syrup",
  "liquid": "syrup",

  // Drops (eye, ear, nasal)
  "eye drops": "drop",
  "eye drop": "drop",
  "ear drops": "drop",
  "ear drop": "drop",
  "nasal drops": "drop",
  "nasal drop": "drop",
  "nasal spray": "drop",
  "eye spray": "drop",
  "eye ointment": "drop",
  "ophthalmic solution": "drop",
  "ophthalmic suspension": "drop",
  "otic solution": "drop",

  // Injections
  injection: "injection",
  "injection solution": "injection",
  ampoule: "injection",
  infusion: "injection",
  "intravenous infusion": "injection",
  vial: "injection",
  "lyophilized powder for injection": "injection",
  "powder for injection": "injection",
  "powder for solution for injection": "injection",
  "solution for injection": "injection",
  "concentrate for solution for injection": "injection",

  // Topicals / Creams
  cream: "cream",
  ointment: "cream",
  gel: "cream",
  lotion: "cream",
  paste: "cream",
  "topical solution": "cream",
  "topical gel": "cream",
  "topical cream": "cream",
  liniment: "cream",
  "dusting powder": "cream",
  "medicated shampoo": "cream",
  foam: "cream",
  spray: "cream",
  "topical spray": "cream",

  // Inhalers
  inhaler: "inhaler",
  "inhaler solution": "inhaler",
  "dry powder inhaler": "inhaler",
  "metered dose inhaler": "inhaler",
  "pressurised inhalation": "inhaler",
  "inhalation solution": "inhaler",
  "inhalation powder": "inhaler",
  "nebuliser solution": "inhaler",

  // Powders / Sachets / Granules
  powder: "powder",
  granules: "powder",
  sachet: "powder",
  "oral powder": "powder",
  "oral granules": "powder",
  "effervescent powder": "powder",
  "powder for oral solution": "powder",
  "powder for oral suspension": "powder",

  // Suppositories / Pessaries
  suppository: "suppository",
  suppositories: "suppository",
  pessary: "suppository",
  pessaries: "suppository",
  "rectal solution": "suppository",
  "rectal suspension": "suppository",
  enema: "suppository",
};

export function getDrugIconKey(dosageForm?: string | null): string {
  if (!dosageForm) return "generic";
  return DOSAGE_FORM_ICON[dosageForm.toLowerCase().trim()] ?? "generic";
}
