"""initial schema

Revision ID: 79e899727f65
Revises: 
Create Date: 2026-06-29 23:22:31.892850
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '79e899727f65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_telegram_id'), 'customers', ['telegram_id'], unique=True)
    op.create_table('delivery_webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_key', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_webhook_events_reference'), 'delivery_webhook_events', ['reference'], unique=False)
    op.create_table('delivery_zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fee_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_fee_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('payment_fee_flat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('offramp_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('handling_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('enable_bank', sa.Boolean(), nullable=False),
    sa.Column('enable_flutterwave', sa.Boolean(), nullable=False),
    sa.Column('enable_crypto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logistics_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('supports_gps', sa.Boolean(), nullable=False),
    sa.Column('supports_tracking_url', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_webhook_events_reference'), 'payment_webhook_events', ['reference'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('nafdac_number', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('controlled_substance', sa.Boolean(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_generic_name'), 'products', ['generic_name'], unique=False)
    op.create_index('ix_products_generic_strength', 'products', ['generic_name', 'strength'], unique=False)
    op.create_index(op.f('ix_products_is_listed'), 'products', ['is_listed'], unique=False)
    op.create_index(op.f('ix_products_nafdac_number'), 'products', ['nafdac_number'], unique=True)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'PHARMACIST', 'PACKAGING', 'DISPATCHER', 'SUPPORT', name='staff_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_telegram_id'), 'staff', ['telegram_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'AWAITING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_APPROVED', 'PROCESSING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', 'REJECTED', name='order_status'), nullable=False),
    sa.Column('rx_status', sa.Enum('NOT_REQUIRED', 'PRESCRIPTION_REQUIRED', 'PRESCRIPTION_UPLOADED', 'PHARMACIST_REVIEW', 'APPROVED_FOR_PAYMENT', 'REJECTED_BY_PHARMACIST', name='rx_status'), nullable=False),
    sa.Column('delivery_status', sa.Enum('NONE', 'PACKAGING', 'READY_FOR_DISPATCH', 'RIDER_ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'NEAR_CUSTOMER', 'DELIVERED', 'FAILED_DELIVERY', 'RETURNED_TO_PHARMACY', name='delivery_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK_TRANSFER', 'FLUTTERWAVE', 'CRYPTO', name='payment_method'), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('offramp_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('handling_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_phone', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_area', sa.String(length=120), nullable=True),
    sa.Column('delivery_landmark', sa.String(length=255), nullable=True),
    sa.Column('delivery_preferred_time', sa.String(length=120), nullable=True),
    sa.Column('delivery_note', sa.Text(), nullable=True),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_code'), 'orders', ['code'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('pharmacist_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.String(length=120), nullable=True),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name', name='uq_alias_name')
    )
    op.create_index(op.f('ix_product_aliases_normalized_name'), 'product_aliases', ['normalized_name'], unique=False)
    op.create_table('product_pricing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('markup_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fixed_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('is_in_stock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('delivery_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider_key', sa.String(length=40), nullable=False),
    sa.Column('provider_delivery_id', sa.String(length=255), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('dropoff_address', sa.Text(), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('package_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_orders_provider_delivery_id'), 'delivery_orders', ['provider_delivery_id'], unique=False)
    op.create_table('delivery_quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('provider_key', sa.String(length=40), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_tracking_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider_key', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('from_value', sa.String(length=60), nullable=True),
    sa.Column('to_value', sa.String(length=60), nullable=False),
    sa.Column('changed_by', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('BANK_TRANSFER', 'FLUTTERWAVE', 'CRYPTO', name='payment_method'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='payment_status'), nullable=False),
    sa.Column('proof_file_id', sa.String(length=255), nullable=True),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_provider_ref'), 'payments', ['provider_ref'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rider_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider_key', sa.String(length=40), nullable=True),
    sa.Column('rider_name', sa.String(length=255), nullable=True),
    sa.Column('rider_phone', sa.String(length=50), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_links')
    op.drop_table('rider_assignments')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_payments_provider_ref'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('order_status_history')
    op.drop_table('order_items')
    op.drop_table('delivery_tracking_events')
    op.drop_table('delivery_quotes')
    op.drop_index(op.f('ix_delivery_orders_provider_delivery_id'), table_name='delivery_orders')
    op.drop_table('delivery_orders')
    op.drop_table('product_pricing')
    op.drop_index(op.f('ix_product_aliases_normalized_name'), table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_table('pharmacist_questions')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_code'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_staff_telegram_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_nafdac_number'), table_name='products')
    op.drop_index(op.f('ix_products_is_listed'), table_name='products')
    op.drop_index('ix_products_generic_strength', table_name='products')
    op.drop_index(op.f('ix_products_generic_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_webhook_events_reference'), table_name='payment_webhook_events')
    op.drop_table('payment_webhook_events')
    op.drop_table('logistics_providers')
    op.drop_table('fee_settings')
    op.drop_table('delivery_zones')
    op.drop_index(op.f('ix_delivery_webhook_events_reference'), table_name='delivery_webhook_events')
    op.drop_table('delivery_webhook_events')
    op.drop_index(op.f('ix_customers_telegram_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
