"""pharmacist messages, product requests, prescription links

Revision ID: 8e089711d5fa
Revises: 0bc15722ceaf
Create Date: 2026-06-30 15:17:12.660247
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e089711d5fa'
down_revision: Union[str, None] = '0bc15722ceaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('form', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('delivery_area', sa.String(length=120), nullable=True),
    sa.Column('is_medicine', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacist_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['pharmacist_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacist_messages_question_id'), 'pharmacist_messages', ['question_id'], unique=False)
    op.add_column('pharmacist_questions', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'pharmacist_questions', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.add_column('prescriptions', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.add_column('prescriptions', sa.Column('question_id', sa.Uuid(), nullable=True))
    op.add_column('prescriptions', sa.Column('file_type', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'prescriptions', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'prescriptions', 'pharmacist_questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'file_type')
    op.drop_column('prescriptions', 'question_id')
    op.drop_column('prescriptions', 'product_id')
    op.drop_constraint(None, 'pharmacist_questions', type_='foreignkey')
    op.drop_column('pharmacist_questions', 'product_id')
    op.drop_index(op.f('ix_pharmacist_messages_question_id'), table_name='pharmacist_messages')
    op.drop_table('pharmacist_messages')
    op.drop_table('product_requests')
    # ### end Alembic commands ###
