"""add crypto_payments

Revision ID: c75171994388
Revises: 79e899727f65
Create Date: 2026-06-30 00:00:30.997576
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c75171994388'
down_revision: Union[str, None] = '79e899727f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('network', sa.String(length=40), nullable=False),
    sa.Column('token', sa.String(length=40), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'CONFIRMED', 'SETTLED', 'REJECTED', name='crypto_status'), nullable=False),
    sa.Column('naira_settled', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_payments_tx_hash'), 'crypto_payments', ['tx_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_payments_tx_hash'), table_name='crypto_payments')
    op.drop_table('crypto_payments')
    # ### end Alembic commands ###
