"""add customer_messages and customer_notes tables

Revision ID: c7814c98029a
Revises: fc06fc22b3ea
Create Date: 2026-06-30 22:52:33.223482
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c7814c98029a'
down_revision: Union[str, None] = 'fc06fc22b3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('admin_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_notes_customer_id'), 'customer_notes', ['customer_id'], unique=False)
    op.create_table('customer_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('attachment_file_id', sa.String(length=255), nullable=True),
    sa.Column('related_order_id', sa.Uuid(), nullable=True),
    sa.Column('message_purpose', sa.String(length=50), nullable=True),
    sa.Column('delivery_status', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_messages_customer_id'), 'customer_messages', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_messages_customer_id'), table_name='customer_messages')
    op.drop_table('customer_messages')
    op.drop_index(op.f('ix_customer_notes_customer_id'), table_name='customer_notes')
    op.drop_table('customer_notes')
    # ### end Alembic commands ###
