"""add customer email capture fields

Revision ID: cae7aa5fcc9f
Revises: 2629724af28f
Create Date: 2026-06-30 18:07:15.536727
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cae7aa5fcc9f'
down_revision: Union[str, None] = '2629724af28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_contact_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('old_email', sa.String(length=255), nullable=True),
    sa.Column('new_email', sa.String(length=255), nullable=True),
    sa.Column('source_flow', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_contact_events_customer_id'), 'customer_contact_events', ['customer_id'], unique=False)
    op.create_table('customer_preferences',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('receive_order_updates', sa.Boolean(), nullable=False),
    sa.Column('receive_product_request_updates', sa.Boolean(), nullable=False),
    sa.Column('receive_pharmacist_replies', sa.Boolean(), nullable=False),
    sa.Column('receive_delivery_updates', sa.Boolean(), nullable=False),
    sa.Column('receive_promotions', sa.Boolean(), nullable=False),
    sa.Column('receive_community_updates', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=True))
    # Existing customers: no email yet, unverified, opted in (transactional default).
    op.add_column('customers', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('customers', sa.Column('email_collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('email_source', sa.String(length=40), nullable=True))
    op.add_column('customers', sa.Column('email_opt_in', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('customers', sa.Column('email_opt_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('email_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('customers', 'email_verified', server_default=None)
    op.alter_column('customers', 'email_opt_in', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'email_updated_at')
    op.drop_column('customers', 'email_opt_in_at')
    op.drop_column('customers', 'email_opt_in')
    op.drop_column('customers', 'email_source')
    op.drop_column('customers', 'email_collected_at')
    op.drop_column('customers', 'email_verified')
    op.drop_column('customers', 'email')
    op.drop_table('customer_preferences')
    op.drop_index(op.f('ix_customer_contact_events_customer_id'), table_name='customer_contact_events')
    op.drop_table('customer_contact_events')
    # ### end Alembic commands ###
