"""extend product requests into a CRM lead system

Revision ID: fc06fc22b3ea
Revises: cae7aa5fcc9f
Create Date: 2026-06-30 21:22:42.548643
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc06fc22b3ea'
down_revision: Union[str, None] = 'cae7aa5fcc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_request_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_request_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sender_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('attachment_file_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_request_id'], ['product_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_request_messages_product_request_id'), 'product_request_messages', ['product_request_id'], unique=False)
    op.create_table('product_request_status_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_request_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_visible_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_request_id'], ['product_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_request_status_events_product_request_id'), 'product_request_status_events', ['product_request_id'], unique=False)
    op.add_column('product_requests', sa.Column('customer_phone', sa.String(length=50), nullable=True))
    op.add_column('product_requests', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('product_requests', sa.Column('urgency', sa.String(length=20), nullable=True))
    op.add_column('product_requests', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('product_requests', sa.Column('customer_visible_message', sa.Text(), nullable=True))
    op.add_column('product_requests', sa.Column('last_customer_update_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_requests', sa.Column('last_admin_update_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_requests', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_requests', sa.Column('converted_order_id', sa.Uuid(), nullable=True))
    op.add_column('product_requests', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('product_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_foreign_key(None, 'product_requests', 'orders', ['converted_order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_requests', type_='foreignkey')
    op.alter_column('product_requests', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('product_requests', 'closed_at')
    op.drop_column('product_requests', 'converted_order_id')
    op.drop_column('product_requests', 'notified_at')
    op.drop_column('product_requests', 'last_admin_update_at')
    op.drop_column('product_requests', 'last_customer_update_at')
    op.drop_column('product_requests', 'customer_visible_message')
    op.drop_column('product_requests', 'admin_notes')
    op.drop_column('product_requests', 'urgency')
    op.drop_column('product_requests', 'customer_email')
    op.drop_column('product_requests', 'customer_phone')
    op.drop_index(op.f('ix_product_request_status_events_product_request_id'), table_name='product_request_status_events')
    op.drop_table('product_request_status_events')
    op.drop_index(op.f('ix_product_request_messages_product_request_id'), table_name='product_request_messages')
    op.drop_table('product_request_messages')
    # ### end Alembic commands ###
