"""Import all models so Base.metadata is fully populated (Alembic, create_all)."""
from app.models.admin import (
    AdminActivityLog,
    AdminRoleAssignment,
    AdminUser,
    Permission,
    Role,
    RolePermission,
)
from app.models.base import Base, TimestampMixin
from app.models.catalog import PriceHistory, Product, ProductAlias, ProductIdentifier, ProductPricing, ProductScanAttempt
from app.models.crypto import CryptoPayment, CryptoStatus
from app.models.logistics import (
    DeliveryOrder,
    DeliveryQuote,
    DeliveryTrackingEvent,
    DeliveryWebhookEvent,
    LogisticsProvider,
    RiderAssignment,
    TrackingLink,
)
from app.models.ops import (
    AuditLog,
    DeliveryZone,
    FeeSetting,
    PharmacistMessage,
    PharmacistQuestion,
    Prescription,
    ProductRequest,
    ProductRequestMessage,
    ProductRequestStatus,
    ProductRequestStatusEvent,
    RequestUrgency,
    Staff,
    StaffRole,
)
from app.models.reminders import (
    MedicationReminder,
    MedicationReminderEvent,
    ReminderConsent,
    ReminderEventStatus,
    ReminderSource,
    ReminderStatus,
)
from app.models.orders import (
    Customer,
    CustomerContactEvent,
    CustomerMessage,
    CustomerNote,
    CustomerPreferences,
    DeliveryStatus,
    Order,
    OrderItem,
    OrderStatus,
    OrderStatusHistory,
    PaymentMethod,
    RxStatus,
)
from app.models.payments import Payment, PaymentStatus, PaymentWebhookEvent

__all__ = [
    "Base",
    "TimestampMixin",
    "MedicationReminder",
    "MedicationReminderEvent",
    "ReminderConsent",
    "ReminderEventStatus",
    "ReminderSource",
    "ReminderStatus",
    "Product",
    "ProductAlias",
    "ProductIdentifier",
    "ProductPricing",
    "ProductScanAttempt",
    "PriceHistory",
    "CryptoPayment",
    "CryptoStatus",
    "Customer",
    "CustomerContactEvent",
    "CustomerMessage",
    "CustomerNote",
    "CustomerPreferences",
    "Order",
    "OrderItem",
    "OrderStatusHistory",
    "OrderStatus",
    "RxStatus",
    "DeliveryStatus",
    "PaymentMethod",
    "Payment",
    "PaymentStatus",
    "PaymentWebhookEvent",
    "Staff",
    "StaffRole",
    "FeeSetting",
    "DeliveryZone",
    "PharmacistQuestion",
    "PharmacistMessage",
    "Prescription",
    "ProductRequest",
    "ProductRequestMessage",
    "ProductRequestStatusEvent",
    "ProductRequestStatus",
    "RequestUrgency",
    "AuditLog",
    "LogisticsProvider",
    "DeliveryQuote",
    "DeliveryOrder",
    "RiderAssignment",
    "TrackingLink",
    "DeliveryTrackingEvent",
    "DeliveryWebhookEvent",
    "AdminUser",
    "AdminRoleAssignment",
    "AdminActivityLog",
    "Role",
    "Permission",
    "RolePermission",
]
